# Generated by Django 5.0.6 on 2024-06-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('blog_image', models.ImageField(upload_to='blog_content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('id_proof', models.ImageField(upload_to='id_proof/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.blog_table')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='blog_table',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.user_table'),
        ),
    ]
