# Generated by Django 5.0.6 on 2024-06-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='password',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
