# Generated by Django 5.0.6 on 2024-07-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_user_table_password_alter_user_table_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_table',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='blog_content/'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='id_proof',
            field=models.ImageField(blank=True, upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
