# Generated by Django 5.0.6 on 2024-07-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_remove_comment_table_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_proof',
            field=models.ImageField(blank=True, upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
