# Generated by Django 5.0.6 on 2024-07-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_profile_id_proof_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
