# Generated by Django 5.0.6 on 2024-07-17 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_blog_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_hidden',
        ),
    ]
