# Generated by Django 5.0.6 on 2024-07-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_remove_blog_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(max_length=150),
        ),
    ]
