# Generated by Django 5.0.6 on 2024-07-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
