# Generated by Django 5.0.6 on 2024-07-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_alter_blog_status_alter_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
